### PR TITLE
SAXParser improvements

### PR DESCRIPTION
**Pull request by mauretto78**
- handing files with no <target> nodes

### CODE REVIEW

**Review by Ostico — COMMENTED** [review]
I see when the variable `$this->segmentHasTarget` is set to true, but i don't see when it is reset to false

**Comment by mauretto78** [comment]
@Ostico I update the PR with the following fixes:

- `$this->segmentHasTarget` is now resetted (at line 407) when leaving a `<trans-unit>` (`<unit>` for Xliff 2.*)
- I introduced a new property called `$segmentPositionInTu` for handling multiple `<segment>` with emply `<target>` inside a `<unit`> (only for Xliff 2.*)

Cheers

**Review by Ostico — CHANGES_REQUESTED** [review]
Can you add some tests for xliff 1.2 with more complex structures?

**Comment by mauretto78** [comment]
@Ostico I update the PR just now with the correct handling for xliff 1.* files with missing `<target>` nodes.

I added a quite complex test.

Please note that I updated the documentation also.

**Review by Ostico — APPROVED** [review]

**Pull request merged**
